### ISSUE TITLE
Request: configure Redis for high availability (HA)

### ISSUE THREAD

**Issue by archonic** [lewagon/rails-k8s-demo#5]
I've managed to get what I believe is pretty close to a reasonable production setup using this repo as a foundation 🎉 . I'm currently a little confused about how to make Redis production ready.

I'm still using the @stable/redis chart as a dependency, and I have Sentinel enabled. The issue is that if the master fails, the redis service seems to flip a coin and most of the time will connect to slave instances instead of the master. This causes sidekiq to have `(error) READONLY You can't write against a read only replica.` errors. This problem is described at length here: https://github.com/helm/charts/issues/12851

I believe changes should be made to the redis service, but I'm not sure what those changes would be. Here's what I have in values.yaml to enable HA for redis:
```
redis:
  cluster:
    enabled: true
    slaveCount: 3
  usePassword: false
  networkPolicy.enabled: true
  # Sentinel enables HA
  sentinel:
    enabled: true
```
